# Лекция 3. Числовые типы

## Цели лекции

После этой лекции вы сможете:
- работать с int/float, системами счисления и побитовыми операциями;
- понимать ограничения `float`: особые значения `inf` и `nan`, сравнение
  через `math.isclose`, банкирское округление;
- применять `Decimal`/`Fraction` для точных вычислений и `datetime` для дат;
- понимать динамическую типизацию, ссылки и разницу `is` vs `==`.


Python поддерживает разные виды числовых объектов, которые используются для работы с любыми количественными данными.

Основные числовые объекты:
- Целые числа (**integers**)  
- Числа с плавающей точкой (**floating-point**)  
- Комплексные числа (**complex**)  
- Десятичные числа с фиксированной точностью (**decimal**)  
- Рациональные дроби (**fractions**)  

Дополнительно:
- Множества (**sets**) и операции над ними  
- Логические (**boolean**) и побитовые операции  
- Встроенные модули: `math`, `cmath`, `random`, `statistics`  
- Сторонние библиотеки: для работы с векторами, графикой, визуализацией, высокой точностью вычислений  


### Числовые литералы в Python
- **Целые числа (integers):** `1234`, `-24`, `0`
- **Числа с плавающей точкой (floats):** `1.23`, `3.14e-10`, `4E210`
- **Шестнадцатеричные, восьмеричные, двоичные:** `0x9ff`, `0o177`, `0b101010`
- **Комплексные числа (complex):** `3+4j`, `3.0+4.0j`, `3J`
- **Булевы значения (booleans):** `True`, `False` – в Python это тоже числа,
  подробнее в конце лекции

Литералом записываются только эти типы. Остальные числовые типы создаются вызовом
конструктора и живут в стандартной библиотеке: `Decimal('1.0')`, `Fraction(1, 3)`.
Им, как и системам счисления с побитовыми операциями, отведены отдельные разделы.

In [1]:
# Примеры числовых литералов
a = 1234       # целое число
pi = 3.1415    # число с плавающей точкой
a, pi

(1234, 3.1415)

In [2]:
c1 = 3 + 4j         # комплексное число
c2 = complex(2, -3) # другой способ задать комплексное число
c2

(2-3j)

In [3]:
flag1 = True
flag2 = bool("text")   # непустая строка -> True

### Операторы выражений в Python
#### Основные группы операторов:
- **Арифметические:** `+`, `-`, `*`, `/`, `//`, `%`, `**`  
- **Сравнения:** `<`, `<=`, `>`, `>=`, `==`, `!=`  
- **Логические:** `and`, `or`, `not`  
- **Побитовые:** `&`, `|`, `^`, `<<`, `>>`, `~`  
- **Операторы принадлежности и идентичности:** `in`, `not in`, `is`, `is not`  
- **Другие:**  
  - `x if y else z` – тернарный оператор (выбор по условию)  
  - `lambda` – анонимные функции  
  - `:=` – оператор присваивания в выражениях (walrus operator)  
  - `@` – матричное умножение (обычно используется в библиотеках, например NumPy)  

> Многие операторы работают не только с числами, но и со строками, списками, словарями, множествами.

In [4]:
# Арифметика
print(7 + 3)     # 10
print(7 / 3)     # 2.333... (обычное деление)
print(7 // 3)    # 2 (целочисленное деление)
print(7 % 3)     # 1 (остаток)
print(2 ** 5)    # 32 (возведение в степень)

10
2.3333333333333335
2
1
32


In [5]:
# Сравнения и логика
print(5 > 3)           
print(5 == 3)          
print((5 > 3) and (2 < 1))  

True
False
False


In [6]:
# Тернарный оператор
x = 10
print("even" if x % 2 == 0 else "odd")  

even


In [7]:
# Принадлежность
print(2 in [1, 2, 3])      # True
print(2 not in [1, 2, 3])  # False

True
False


### Приоритет операторов 
Когда в выражении используется несколько операторов, порядок их выполнения задаётся **правилами приоритета**:
- Обычно операторы с одинаковым приоритетом выполняются **слева направо**.  
- Исключения:  
  - **Возведение в степень `**`** выполняется справа налево.  
  - **Сравнения** могут "цепляться" (`X < Y < Z`).  

In [8]:
print(2 + 3 * 4)        
print((2 + 3) * 4)      

print(2 ** 3 ** 2)      # 512 (сначала 3**2=9, потом 2**9)
print((2 ** 3) ** 2)    # 64  (если скобки: сначала 2**3, потом возведение в квадрат)

print(1 < 2 < 3)        # True  (цепное сравнение: 1<2 и 2<3)
print(1 < 2 and 2 < 3)  # То же самое, но длиннее

# Логические и арифметические операторы
print(2 + 3 > 4 and 5 < 10)  # True

14
20
512
64
True
True
True


### Смешанные типы в выражениях
- В Python можно смешивать разные числовые типы в одном выражении.  
- **Правило**: более простой тип автоматически преобразуется к более сложному.  
- Порядок "сложности" типов:  
  `int` → `float` → `complex`.  
- Итоговый результат имеет тот же тип, что и самый «сложный» из операндов.  

Примеры:  
- `40 + 3.14` → целое число (`int`) преобразуется в число с плавающей точкой (`float`).  
- Любая операция с комплексным числом превращает результат в `complex`.  
- Равенство сравнивает разные типы: `3 == 3.0 → True`.  

Ручные преобразования:  
- `int(3.1415)` → 3 (усечение дробной части).  
- `float(3)` → 3.0.  

Автоматические преобразования работают **только для чисел**. Попытка сложить строку и число вызовет ошибку.  


In [9]:
# Автоматические преобразования
print(40 + 3.14)   
print(2 + 3j + 5)  

43.14
(7+3j)


### Форматы отображения чисел
- Иногда результат вычислений с `float` выглядит странно:  
  `1.1 + 2.2 → 3.3000000000000003`.  
- Это не ошибка Python, а ограничение двоичной арифметики процессора.  
- Обычно Python сам выводит меньше знаков, но иногда появляются "лишние".  
- Для управления выводом используются **форматирование строк** (`%`, `format`, f-строки).  
- Разные функции для вывода:  
  - `repr()` – формальный вид (как в коде, используется в интерактивных эхо).  
  - `str()` – человеко-дружественный вид (используется в `print`).  


In [10]:
# Ограничения float
print(1.1 + 2.2)   

3.3000000000000003


In [11]:
# Форматирование вывода
num = 1.1 + 2.2
print('%e' % num)      # экспоненциальный формат 
print('%.1f' % num)    # округление до 1 знака после запятой
print(f'{num:e}')      # f-строка, экспоненциальный формат
print(f'{num:.1f}')    # f-строка, округление 

3.300000e+00
3.3
3.300000e+00
3.3


In [12]:
# Разница repr и str
print(repr('hack'))   # "'hack'" (как код)
print(str('hack'))    # "hack"  (как для пользователя)

'hack'
hack


### Особые значения `float`: `inf` и `nan`

Кроме обычных чисел стандарт IEEE 754 даёт два особых значения, и оба встречаются
в реальных данных.

- **`inf`** – бесконечность: `float("inf")`, результат переполнения или деления
  на очень малое. С ней можно сравнивать и считать: `1 / inf` даёт `0.0`.
- **`nan`** – «не число» (not a number): результат неопределённой операции вроде
  `inf - inf`, а также маркер пропуска в данных (его вы увидите в лекции про Pandas).

Главная особенность `nan`: **он не равен сам себе**. `nan == nan` даёт `False`,
и это не ошибка Python, а требование стандарта. Проверять надо через `math.isnan()`.

In [13]:
import math

inf = float("inf")
print(inf, -inf, "| inf больше любого числа:", inf > 10**100)
print("1 / inf =", 1 / inf, "| inf - inf =", inf - inf)

nan = float("nan")
print("nan == nan:", nan == nan)        # False: у nan нет равенства
print("math.isnan(nan):", math.isnan(nan))   # правильная проверка

# Тонкость: оператор in сначала сравнивает по тождеству, поэтому найдёт
print("nan in [nan]:", nan in [nan])


inf -inf | inf больше любого числа: True
1 / inf = 0.0 | inf - inf = nan
nan == nan: False
math.isnan(nan): True
nan in [nan]: True


### Сравнение и округление `float`

Два места, где интуиция подводит.

**Сравнение.** `0.1 + 0.2 == 0.3` даёт `False`: в двоичной записи этих чисел нет
точно. Сравнивать нужно с допуском – `math.isclose()`, либо считать в `Decimal`,
если речь о деньгах.

**Округление.** `round()` использует «банкирское» округление (half-to-even):
половина уходит к **чётному** соседу. Поэтому `round(0.5)` даёт `0`, а `round(1.5)`
даёт `2`. Так сделано, чтобы при массовом округлении ошибки не накапливались
в одну сторону.

Отдельный случай – `round(2.675, 2)` даёт `2.67`, и банкирское округление здесь
ни при чём: само `2.675` хранится в памяти **ниже** середины между `2.67` и `2.68`.
Точные значения разберём на отдельных экранах – без них оба правила выглядят
произволом.

In [14]:
import math

# Сравнение с допуском
print("0.1 + 0.2 == 0.3:", 0.1 + 0.2 == 0.3)
print("math.isclose(0.1 + 0.2, 0.3):", math.isclose(0.1 + 0.2, 0.3))
print("с относительным допуском:", math.isclose(1000.0, 1000.1, rel_tol=1e-3))


0.1 + 0.2 == 0.3: False
math.isclose(0.1 + 0.2, 0.3): True
с относительным допуском: True


In [15]:
# Банкирское округление: половина уходит к чётному
for x in (0.5, 1.5, 2.5, 3.5, -1.5):
    print(f"round({x:>5}) = {round(x)}")

print("round(2.675, 2) =", round(2.675, 2), "- 2.675 хранится чуть меньше")


round(  0.5) = 0
round(  1.5) = 2
round(  2.5) = 2
round(  3.5) = 4
round( -1.5) = -2
round(2.675, 2) = 2.67 - 2.675 хранится чуть меньше


### Почему `0.1 + 0.2` не даёт `0.3`

Мантисса `float` **двоичная**, поэтому точно представимы только дроби со
знаменателем – степенью двойки: `0.5`, `0.25`, `0.125`. Десятичная `0.1` такой
не является, и в памяти вместо неё лежит ближайшее двоичное приближение.

Увидеть его можно форматированием с большим числом знаков: `f"{x:.20f}"`.
Обычная печать показывает короткую запись, которой достаточно, чтобы число
прочиталось обратно тем же значением, – поэтому `print(0.1)` и даёт `0.1`.

In [16]:
# Что на самом деле лежит в памяти
for x in (0.1, 0.2, 0.3):
    print(f"{x}  ->  {x:.20f}")

print("\n0.1 + 0.2 =", 0.1 + 0.2)
print(f"подробнее ->  {0.1 + 0.2:.20f}")

0.1  ->  0.10000000000000000555
0.2  ->  0.20000000000000001110
0.3  ->  0.29999999999999998890

0.1 + 0.2 = 0.30000000000000004
подробнее ->  0.30000000000000004441


### `round(2.675, 2)`: почему `2.67`

Здесь дело не в правиле округления, а в том, каким числом оказался литерал.

- `2.675` хранится **ниже** середины между `2.67` и `2.68` – округляется вниз.
- `2.665` хранится **выше** середины между `2.66` и `2.67` – округляется вверх.

Оба дают `2.67`, хотя по школьному правилу должны были дать `2.68` и `2.67`.
Никакой «ровной половины» в памяти не существует, поэтому банкирское правило
к этим случаям даже не применяется.

Практический вывод: для денег `round` по `float` не даст того, что ожидает
бухгалтерия. Для этого есть `Decimal` – он дальше в этой лекции.

In [17]:
for x in (2.675, 2.665):
    print(f"{x}  ->  {x:.20f}   round(x, 2) = {round(x, 2)}")

2.675  ->  2.67499999999999982236   round(x, 2) = 2.67
2.665  ->  2.66500000000000003553   round(x, 2) = 2.67


### Операторы деления в Python
- `/` – **обычное деление (true division)**, результат всегда `float`.
- `//` – **деление с округлением вниз (floor division)**, результат `int` или `float` в зависимости от типов операндов.
- `%` – **остаток от деления (modulus)**.
- `divmod(x, y)` – сразу возвращает `(частное, остаток)` в виде кортежа.


In [18]:
# Обычное деление (true division)
print(10 / 4)      
print(10 / 4.0)    

# Деление с округлением вниз (floor division)
print(10 // 4)     # 2   (результат int)
print(10 // 4.0)   # 2.0 (результат float)

# Приведение к целому
print(int(10 // 4.0))  # 2

# Остаток от деления (modulus)
print(10 % 3)      # 1
print(10 % 3.0)    # 1.0

# Частное и остаток сразу
print(divmod(10, 3))   # (3, 1)


2.5
2.5
2
2.0
2
1
1.0
(3, 1)


### Деление: округление вниз (floor) против усечения (truncation)
- `//` – **деление с округлением вниз** (floor division).  
  Оно всегда округляет результат к ближайшему целому числу, которое **меньше или равно** результату деления.  
- `math.trunc()` – **усечение дробной части** (truncation).  
  Оно просто «отрезает» дробную часть, двигаясь к нулю, а не обязательно вниз.  
- Для положительных чисел поведение `//` и `trunc()` совпадает.  
- Для отрицательных чисел появляется разница: `//` округляет «вниз» (к меньшему), а `trunc()` округляет к нулю.  


In [19]:
import math

print(math.floor(2.5))    # 2
print(math.floor(-2.5))   # -3

print(math.trunc(2.5))    # 2
print(math.trunc(-2.5))   # -2

print(5 / 2, 5 // 2)      # 2.5  2
print(5 / -2, 5 // -2)    # -2.5 -3

print(math.trunc(5 / -2)) # -2 (усечение)

2
-3
2
-2
2.5 2
-2.5 -3
-2


### Целые числа и их точность (Integer Precision)
- Целые числа в Python имеют **неограниченную точность**.  
- Ограничение – только объём памяти.  
- Очень большие числа обрабатываются медленнее.  
- Для вывода сверхдлинных чисел есть ограничение (`sys.set_int_max_str_digits`).  


In [20]:
import sys

sys.get_int_max_str_digits()

4300

In [21]:
# Примеры работы с большими числами
print(999999999999999999999999999999 + 1)

print(2 ** 269)  # Возведение в большую степень

1000000000000000000000000000000
948568795032094272909893509191171341133987714380927500611236528192824358010355712


In [22]:
# Попытка вывести слишком большое число
try:
    x = 2 ** 1000000
    print(x)
except ValueError as e:
    print("Ошибка:", e)

Ошибка: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit


### Комплексные числа (Complex Numbers)
- Записываются как `a + bj` (где `a` – действительная часть, `b` – мнимая).  
- Поддерживают стандартные арифметические операции.  
- Доступ к частям: `.real` и `.imag`.  
- Дополнительные функции – в модуле `cmath`.  


In [23]:
print(1j * 1J)       
print(2 + 1j * 3)    
print((2 + 1j) * 3)  

z = 2 - 3j
print(z.real) 
print(z.imag) 

(-1+0j)
(2+3j)
(6+3j)
2.0
-3.0


### Шестнадцатеричные, восьмеричные и двоичные числа
- В Python можно записывать целые числа не только в десятичной системе, но и в **hex (16-ричной)**, **oct (8-ричной)** и **bin (2-ичной)**.  
- Запись:  
  - `0x` – шестнадцатеричная форма (цифры `0–9`, буквы `A–F`).  
  - `0o` – восьмеричная форма (цифры `0–7`).  
  - `0b` – двоичная форма (цифры `0–1`).  
- Независимо от формы записи, в памяти число хранится одинаково.  
- Встроенные функции:  
  - `bin()`, `oct()`, `hex()` – перевод числа в строку в другой системе.  
  - `int(str, base)` – перевод строки в число с указанием системы счисления.  
- Форматирование строк (`%`, `.format()`, f-строки) тоже позволяет выводить числа в разных системах.  


In [24]:
# Запись чисел в разных системах
print(0x01, 0x10, 0xFF)       # 1, 16, 255 (hex)
print(0o1, 0o20, 0o377)       # 1, 16, 255 (octal)
print(0b1, 0b10000, 0b11111111)  # 1, 16, 255 (binary)

# Перевод числа в разные системы
print(oct(64), hex(64), bin(64))

# Обратный перевод строки в число
print(int('100', 8))   
print(int('1000000', 2))  # 64 (binary → decimal)

1 16 255
1 16 255
1 16 255
0o100 0x40 0b1000000
64
64


In [25]:
# Форматирование строк
print('%o, %x, %#X' % (64, 255, 255))                # старый стиль
print('{:o}, {:b}, {:x}, {:#X}'.format(64, 64, 255, 255))  # .format
print(f'{64:o}, {64:b}, {255:x}, {255:#X}')          # f-строки

100, ff, 0XFF
100, 1000000, ff, 0XFF
100, 1000000, ff, 0XFF


In [26]:
# Большие числа тоже работают
X = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFF
print(X)        # десятичное представление
print(oct(X))   # восьмеричное
print(bin(X)[:70] + '...')  # двоичное 

5192296858534827628530496329220095
0o17777777777777777777777777777777777777
0b11111111111111111111111111111111111111111111111111111111111111111111...


### Побитовые операции в Python
- Python поддерживает работу с числами на уровне **битов** (как в C).  
- Основные операции:  
  - `<<` – сдвиг влево (умножение на степень 2).  
  - `>>` – сдвиг вправо (деление на степень 2).  
  - `&` – побитовое И (AND).  
  - `|` – побитовое ИЛИ (OR).  
  - `^` – побитовое исключающее ИЛИ (XOR).  
  - `~` – побитовое отрицание (NOT).  
- Часто применяются для работы с **флагами, пакетами данных, бинарными протоколами**.  
- Удобно комбинировать с **двоичными (`0b...`) и шестнадцатеричными (`0x...`) литералами**.  
- Метод `.bit_length()` позволяет узнать, сколько бит нужно для представления числа.  


In [27]:
x = 1       # двоичное: 0001
print(x << 2)   # 4  -> 0100 (сдвиг влево)
print(x | 3)    # 3  -> 0011 (OR: хотя бы один бит = 1)
print(x & 3)    # 1  -> 0001 (AND: оба бита = 1)

4
3
1


In [28]:
# Работа с бинарными литералами
X = 0b0001
print(bin(X << 2))        # 
print(bin(X | 0b0011))    # 
print(bin(X & 0b11))      # 

0b100
0b11
0b1


### Подчёркивания в числах (underscore separators)
- Начиная с **Python 3.6**, в числовых литералах можно использовать символ `_` для удобного чтения.  
- Подчёркивания **не влияют на значение числа**, они игнорируются интерпретатором.  
- Ограничения: нельзя ставить `_` в начале, в конце и подряд несколько.  
- В выводе Python подчёркивания **не сохраняются** – только в исходном коде.  

In [29]:
# Примеры использования подчёркиваний
print(999_999_999 == 999999999)     
print(0xFF_FF == 0xFFFF)            
print(3.141_592 == 3.141592) 

True
True
True


### Встроенные числовые инструменты
- **Встроенные функции**: `pow`, `abs`, `round`, `int`, `sum`, `min`, `max`.
- **Модуль `math`**: константы (`pi`, `e`), функции (`sin`, `sqrt`, `floor`, `trunc`).
- **Округление** `round(x, n)`:
  - Если n > 0, то округление идёт до указанного количества знаков после запятой.
  - Если n = 0, то округляется до целого.
  - Если n < 0, то округление идёт влево от десятичной точки – до десятков, сотен, тысяч и т.д.
  - `math.floor` и `math.trunc` разбирались в разделе про деление.
  - Форматирование строками (`f'{x:.2f}'`) – вывод числа как строки.
- **Несколько способов вычислить корень**: `math.sqrt(x)`, `x ** 0.5`, `pow(x, 0.5)`.
- **Модуль `statistics`**: среднее (`mean`), медиана (`median`) и другие функции.
- **Модуль `random`**: генерация случайных чисел, выбор элементов и перемешивание списков.
- **Методы самих чисел**: у `float` – `as_integer_ratio()` и `is_integer()`,
  у `int` – `bit_length()`.

In [30]:
import math
import statistics
import random

print(math.pi, math.e)
print(math.sin(2 * math.pi / 180))
print(math.sqrt(2))
print(abs(-62.0), sum([1, 2, 3, 4]))
print(min(3, 1, 2, 4), max(3, 1, 2, 4))

3.141592653589793 2.718281828459045
0.03489949670250097
1.4142135623730951
62.0 10
1 4


In [31]:
# У round второй аргумент задаёт, куда считать знаки
print("n > 0:", round(2.567, 2))                            # знаки после точки
print("n = 0:", round(2.567))                               # до целого
print("n < 0:", round(2567, -1), round(2567, -2), round(2567, -3))   # десятки, сотни, тысячи

print(f"{2.567:.2f}")   # форматирование даёт строку, а не число

n > 0: 2.57
n = 0: 3
n < 0: 2570 2600 3000
2.57


In [32]:
# Три способа вычислить корень
print(math.sqrt(144), 144 ** 0.5, pow(144, 0.5))

12.0 12.0 12.0


In [33]:
# Методы float
x = 3.5
print(x.as_integer_ratio())
print(x.is_integer())


(7, 2)
False


In [34]:
# Методы int
n = 42
print(n.bit_length())


6


In [35]:
# Модуль statistics
print(statistics.mean([1, 2, 4, 5, 7]))   
print(statistics.median([1, 2, 4, 5, 7])) 

3.8
4


In [36]:
print(random.random())         # случайное число [0,1)
print(random.randint(1, 10))   # случайное целое число

0.3377151823653364
8


In [37]:
print(random.choice(['Pizza', 'Tacos', 'Lasagna']))
suits = ['hearts', 'diamonds', 'clubs', 'spades']
random.shuffle(suits)
print(suits)

Lasagna
['diamonds', 'hearts', 'clubs', 'spades']


### Decimal – десятичные числа с фиксированной точностью
- Обычные `float` в Python хранят значения в двоичном формате, из-за чего возможны ошибки округления  
- Пример: `0.1 + 0.1 + 0.1 - 0.3` ≠ `0.0`, а даёт маленькую погрешность  
- Модуль `decimal` позволяет работать с **десятичными числами фиксированной точности**  
- Создание: `Decimal('0.1')` (лучше передавать строки, чтобы избежать ошибок float)  
- Можно задавать **глобальную точность** и правила округления через `decimal.getcontext()`  
- Используется там, где важна точность вычислений (например, финансы)  

In [38]:
from decimal import Decimal, getcontext
import decimal

# Ошибка округления с float
print(0.1 + 0.1 + 0.1 - 0.3)

# Работа с Decimal
print(Decimal('0.1') + Decimal('0.1') + Decimal('0.1') - Decimal('0.3'))

5.551115123125783e-17
0.0


In [39]:
# Разная точность
print(Decimal('0.1') + Decimal('0.10') + Decimal('0.1000') - Decimal('0.30'))

# Создание из float
print(Decimal(0.1) + Decimal(0.1) + Decimal(0.1) - Decimal(0.3))

0.0000
2.775557561565156540423631668E-17


In [40]:
# Управление точностью
print(decimal.Decimal(1) / decimal.Decimal(7))  # по умолчанию
getcontext().prec = 4
print(decimal.Decimal(1) / decimal.Decimal(7))  # с точностью 4 знака

0.1428571428571428571428571429
0.1429


### Fraction – рациональные числа
- Модуль `fractions` реализует работу с **рациональными числами** (числитель и знаменатель)  
- Дроби создаются через `Fraction(числитель, знаменатель)`  
- При создании автоматически сокращаются (например, `Fraction(4, 6)` → `2/3`)  
- Можно создавать из строк, включая десятичные (`Fraction('0.25') → 1/4`)  
- Дроби участвуют в обычных арифметических операциях (+, −, *, /), результат всегда точный  
- В отличие от `float`, дроби не теряют точность при вычислениях  
- Подходят для задач, где важна **математическая точность** (например, вычисления с долями)  


In [41]:
from fractions import Fraction
from decimal import Decimal

# Создание дробей
x = Fraction(1, 3)
y = Fraction(4, 6)  # автоматически сократится до 2/3

print(x, y)        # 1/3  2/3
print(x + y)       # 1
print(x - y)       # -1/3
print(x * y)       # 2/9


1/3 2/3
1
-1/3
2/9


In [42]:
# Создание из строк
print(Fraction("0.25"))   # 1/4
print(Fraction("1.25"))   # 5/4

# Сравнение с float
a = 1/3
b = 4/6
print(a, b, a+b, a*b)  # приближённые значения

1/4
5/4
0.3333333333333333 0.6666666666666666 1.0 0.2222222222222222


In [43]:
# Сравнение подходов
print(1/3)                # float
print(Fraction(1, 3))     # Fraction

0.3333333333333333
1/3


### Дата и время: `datetime`

Модуль `datetime` – стандартные типы для дат и времени: создание, форматирование
в строку (`strftime`), разбор из строки (`strptime`) и арифметика через `timedelta`.

In [44]:
from datetime import date, datetime, timedelta

d = date(2026, 8, 23)
print(d, "| год:", d.year, "| день недели (0=Пн):", d.weekday())

dt = datetime(2026, 8, 23, 14, 30)
print("Формат:", dt.strftime("%d.%m.%Y %H:%M"))                 # дата -> строка
print("Разбор:", datetime.strptime("2026-12-31", "%Y-%m-%d"))   # строка -> дата

print("Через 10 дней:", d + timedelta(days=10))                 # арифметика дат
print("Дней до НГ:", (date(2027, 1, 1) - d).days)

2026-08-23 | год: 2026 | день недели (0=Пн): 6
Формат: 23.08.2026 14:30
Разбор: 2026-12-31 00:00:00
Через 10 дней: 2026-09-02
Дней до НГ: 131


### Множества (set): что дальше

Основы – создание, операции `-`, `|`, `&`, `^`, скорость `in` – разбирались
в лекции про типы данных. Здесь идём дальше.

- **Методы вместо операторов**: `.add(x)`, `.update(iterable)`, `.remove(x)`,
  `.intersection(other)` – то же, что `&`, но читается как обычный вызов.
- **Множества итерируемы, но не индексируемы**: `for x in s` работает, `s[0]` – нет.
- Дальше: `frozenset`, генераторы множеств и прикладные задачи.

> Порядок элементов в множестве **не определён** и меняется от запуска к запуску:
> вывод на слайде и у вас на экране совпадать не обязан. Нужен предсказуемый
> порядок – сортируйте через `sorted()`.


In [45]:
# Множество можно собрать из любой последовательности
x = set("abcde")
y = {99, "b", "y", 1.2}

print(sorted(x, key=str))
print(sorted(y, key=str))


['a', 'b', 'c', 'd', 'e']
[1.2, 99, 'b', 'y']


In [46]:
# Методы множеств
z = x.intersection(y)   # то же, что x & y
z.add("HACK")
z.update(["X", "Y"])    # расширение
z.remove("b")           # удаление
print(z)

# Итерация по множеству
for item in {"a", "b", "c"}:
    print(item * 3)

{'HACK', 'Y', 'X'}
aaa
ccc
bbb


### Ограничения множеств и frozenset
- Множества могут содержать **только неизменяемые (immutable, hashable)** объекты  
- В них нельзя помещать списки или словари  
- Можно хранить числа, строки, кортежи (если внутри только неизменяемые объекты)  
- Сравнение в множествах идёт по полному значению  
- Множества сами по себе изменяемы, поэтому **нельзя вложить set в set**  
- Для этого есть специальный тип `frozenset` – неизменяемое множество  
  - Создаётся с помощью `frozenset(iterable)`  
  - Может использоваться внутри обычных множеств  


In [47]:
# Ограничения: только неизменяемые объекты
S = {1.23}

try:
    S.add([1, 2, 3])   # список
except TypeError as e:
    print("Ошибка:", e)

try:
    S.add({"a": 1})    # словарь
except TypeError as e:
    print("Ошибка:", e)


Ошибка: unhashable type: 'list'
Ошибка: unhashable type: 'dict'


In [48]:
# Работает с кортежами
S.add((1, 2, 3))
print(S)

# Проверка принадлежности
print((1, 2, 3) in S)   # True
print((1, 4, 3) in S)   # False

{1.23, (1, 2, 3)}
True
False


In [49]:
# Вложенные множества: используем frozenset
S.add(frozenset("app"))
print(S)

{1.23, (1, 2, 3), frozenset({'a', 'p'})}


### Генераторы множеств (set comprehensions)
- Множества можно создавать не только через литералы `{}` и функцию `set()`, но и с помощью **генераторов множеств**  
- Запись аналогична списковым генераторам, но результатом будет **множество**  
- Синтаксис: `{выражение for переменная in итерируемый_объект}`  
- Все правила множеств сохраняются: элементы уникальны, порядок не гарантируется  
- Можно использовать строки, списки и другие итерируемые объекты  
- Результирующее множество поддерживает все стандартные операции: объединение, пересечение и т.д.  


In [50]:
# Квадраты чисел через set comprehension
S1 = {x ** 2 for x in [1, 2, 3, 4, 4]}
print(S1)  # {16, 1, 4, 9}

# Создание множества символов из строки
S2 = {x for x in "py3X"}
print(S2) 

{16, 1, 4, 9}
{'y', '3', 'X', 'p'}


In [51]:
# Использование выражения для преобразования элементов
S3 = {c * 4 for c in "py3X"}
print(S3)  # {'pppp', 'yyyy', '3333', 'XXXX'}

{'3333', 'yyyy', 'pppp', 'XXXX'}


In [52]:
# Обычные операции с результатами
print(S3 | {"zzzz", "XXXX"})  # объединение
print(S3 & {"zzzz", "XXXX"})  # пересечение

{'zzzz', '3333', 'yyyy', 'pppp', 'XXXX'}
{'XXXX'}


### Зачем нужны множества
- **Отслеживание посещённых элементов**: при обходе графов, деревьев и ссылок
  множество отвечает на вопрос «мы здесь уже были?» за постоянное время.
- **Сравнение без учёта порядка**: два списка с одинаковым составом не равны,
  а множества из них – равны.
- **Разности**: что есть в одной коллекции и чего нет в другой – одной операцией,
  без вложенных циклов.


In [53]:
# Отслеживание посещённых: обход без повторов
graph = {"a": ["b", "c"], "b": ["c"], "c": ["a"]}
visited = set()
queue = ["a"]
while queue:
    node = queue.pop()
    if node in visited:
        continue
    visited.add(node)
    queue.extend(graph[node])
print("обошли:", sorted(visited))

# Сравнение без учёта порядка
L1, L2 = [1, 3, 5, 2, 4], [2, 5, 3, 4, 1]
print("списки равны:", L1 == L2, "| составы равны:", set(L1) == set(L2))

# Разность: что есть в первой коллекции и нет во второй
print("разность:", sorted(set([1, 3, 5, 7]) - set([1, 2, 4, 5, 6])))


обошли: ['a', 'b', 'c']
списки равны: False | составы равны: True
разность: [3, 7]


### Логический тип (Boolean)
- В Python есть отдельный логический тип **bool** с двумя значениями: **True** и **False**.  
- На самом деле `True` и `False` – это подкласс целых чисел `int`, где `True` ведёт себя как `1`, а `False` – как `0`.  
- Главное отличие: они выводятся как слова `True` и `False`, а не как цифры.  
- Это делает код более понятным:  
  - вместо `while 1:` можно писать `while True:`  
  - флаг можно инициализировать как `flag = False`.  
- Но так как `True` и `False` – это числа, возможны неожиданные эффекты:  
  - `True + 4` даёт `5`  
  - `True == 1` вернёт `True`, но `True is 1` – `False`.  


In [54]:
print(type(True))
print(isinstance(True, int))
print(True == 1)             # равно по значению

one = 1                      # через переменную: без SyntaxWarning
print(True is one)           # но это РАЗНЫЕ объекты

print(True or False)
print(True + 4)              # True ведёт себя как 1


<class 'bool'>
True
True
False
True
5


## Динамическая типизация в Python

Объявлять переменные и их типы заранее не нужно: тип определяется во время
выполнения, а не на этапе компиляции. Это сильно отличает Python от языков
со статической типизацией (C, C++, Java).

Присваивание `a = 3` состоит из трёх шагов: создать объект `3`, создать имя `a`,
если его ещё нет, и связать имя с объектом. **Тип хранится в объекте, а не в имени** –
одно и то же имя может по очереди ссылаться на число, строку и список.

Ссылка – это «указатель» от имени на объект, Python разыменовывает их сам.
Каждый объект помнит, сколько ссылок на него ведёт; когда счётчик обнуляется,
объект удаляет сборщик мусора. Имя должно получить значение до первого
обращения, иначе будет `NameError`.

In [55]:
# Тип принадлежит объекту: имя a по очереди ссылается на три разных объекта
a = 3
print(a, type(a), id(a))

a = "hello"
print(a, type(a), id(a))

a = [1, 2, 3]
print(a, type(a), id(a))

3 <class 'int'> 4351729728
hello <class 'str'> 4466297568
[1, 2, 3] <class 'list'> 4471812928


In [56]:
# Ошибка при обращении к неинициализированному имени
try:
    print(bm)     # имя bm ещё не создано
except NameError as e:
    print("Ошибка:", e)

Ошибка: name 'bm' is not defined


### Совместные ссылки (Shared References)
- В Python несколько переменных могут ссылаться на один и тот же объект.  
- Присвоение `b = a` не копирует объект, а делает так, что `b` указывает на тот же объект, что и `a`.  
- Переменные **никогда не ссылаются друг на друга напрямую**, они всегда указывают на объект.  
- Если затем переназначить `a` на новый объект, это никак не затронет `b` – он продолжит ссылаться на старый объект.  
- Объекты неизменяемых типов (например, числа и строки) никогда не меняются "на месте" – новые значения создают новые объекты.  


In [57]:
# Пример shared references
a = 3
b = a   # b указывает на тот же объект, что и a

print("После присваивания b = a:", a, b)

a = "hack"   # теперь a указывает на новый объект (строку)
print("После изменения a:", a, )  # b остался привязан к числу 3
print("b", b)

После присваивания b = a: 3 3
После изменения a: hack
b 3


### Совместные ссылки и изменения "на месте"
- Неизменяемые объекты (числа, строки, кортежи) нельзя менять – при новых значениях создаются новые объекты.  
- Изменяемые объекты (списки, словари, множества) могут изменяться **на месте**.  
- Если две переменные ссылаются на один и тот же изменяемый объект, то изменения, сделанные через одну переменную, будут видны и через другую.  
- Чтобы этого избежать, нужно явно создавать копии объектов (`[:]`, `list()`, `.copy()`, `copy.deepcopy()` и др.).  


In [58]:
# Пример с общими ссылками на изменяемый объект
L1 = [2, 3, 4]
L2 = L1     # L2 и L1 указывают на один и тот же список

In [59]:
L1[0] = 24  # изменяем список "на месте"
print("L1:", L1)
print("L2:", L2)   # L2 тоже "видит" изменения

L1: [24, 3, 4]
L2: [24, 3, 4]


In [60]:
# Создание копии, чтобы избежать совместных изменений
L1 = [2, 3, 4, [1, 2, 3]]
L2 = L1[:]  # копия списка
L1[0] = 24
print("L1:", L1)
print("L2:", L2)   # теперь списки разные

L1: [24, 3, 4, [1, 2, 3]]
L2: [2, 3, 4, [1, 2, 3]]


### Совместные ссылки и равенство объектов
- В Python есть два разных способа проверить «равенство»:
  - `==` сравнивает **значения объектов**.
  - `is` проверяет **идентичность объектов** (ссылаются ли переменные на один и тот же объект).  
- Для изменяемых объектов (`list`, `dict`, `set`):  
  - `==` проверяет совпадение содержимого.  
  - `is` проверяет, действительно ли это один и тот же объект в памяти.  
- Для неизменяемых объектов (например, маленькие числа и строки) Python часто использует кэширование. Поэтому разные переменные могут указывать на один и тот же объект.  
- `id(obj)` возвращает уникальный идентификатор объекта (часто его адрес в памяти).  


In [61]:
# Пример с изменяемыми объектами
L = [1, 2, 3]
M = L
print(L == M)  # True: значения совпадают
print(L is M)  # True: это один и тот же объект


True
True


In [62]:
L = [1, 2, 3]
M = [1, 2, 3]
print(L == M)  # True: значения совпадают
print(L is M)  # False: разные объекты

True
False


In [63]:
# Пример с неизменяемыми объектами (кэширование чисел и строк)
X = 99
Y = 99
print(X == Y)  # True: значения совпадают
print(X is Y)  # True из-за кэширования

True
True


In [64]:
import sys

# Счётчик ссылок - сколько имён и контейнеров держат объект.
# getrefcount всегда добавляет единицу: ссылку своего собственного аргумента
n = 2 ** 1000
print("объект, у которого есть имя:", sys.getrefcount(n))         # имя n плюс аргумент
print("объект без имени:          ", sys.getrefcount(2 ** 1000))  # только аргумент

# Малые целые с версии 3.12 "бессмертны": счётчик зафиксирован и не меняется,
# такой объект не удаляется до конца работы программы
print("бессмертное 99:            ", sys.getrefcount(99), "(это 2**32 - 1)")

объект, у которого есть имя: 2
объект без имени:           1
бессмертное 99:             4294967295 (это 2**32 - 1)


In [65]:
# Кэш малых целых - от -5 до 256. int() из строки нужен, чтобы число
# создалось во время работы, а не было подставлено компилятором
a, b = 256, int("256")
print("256:", a is b)      # True: оба имени ведут в кэш

a, b = 257, int("257")
print("257:", a is b)      # False: за границей кэша создан новый объект

256: True
257: False


## Частые ошибки

- **`int("3.5")` вместо `int(float("3.5"))`.** `int` разбирает только целые
  литералы: дробная строка даёт `ValueError`.
- **Остаток от деления отрицательного числа.** `-7 % 3` в Python даёт `2`,
  а не `-1`, как в C и Java: знак результата совпадает со знаком делителя.
- **`int(math.sqrt(n))` для больших целых.** `sqrt` считает через `float`
  и на больших числах ошибается; целый корень даёт `math.isqrt`.

In [66]:
import math

try:
    int("3.5")
except ValueError as e:
    print("ValueError:", e)

print("-7 % 3 =", -7 % 3, "| 7 % -3 =", 7 % -3)

n = 10 ** 18 - 1
print("math.isqrt:     ", math.isqrt(n))
print("int(math.sqrt): ", int(math.sqrt(n)), "- больше настоящего корня")

ValueError: invalid literal for int() with base 10: '3.5'
-7 % 3 = 2 | 7 % -3 = -2
math.isqrt:      999999999
int(math.sqrt):  1000000000 - больше настоящего корня


## Мини-упражнения


### 1. `to_binary(n)`

Верните двоичную запись неотрицательного числа **без** `bin()` – через побитовые операции.

In [67]:
def to_binary(n):
    if n == 0:
        return "0"
    bits = ""
    while n > 0:
        bits = str(n & 1) + bits   # младший бит
        n >>= 1                    # сдвиг вправо
    return bits

print(to_binary(13))

1101


### 2. `money_sum(prices)`

Точно просуммируйте список цен-строк (без ошибок float). *Подсказка:* `decimal.Decimal`.

In [68]:
from decimal import Decimal

def money_sum(prices):
    return sum((Decimal(p) for p in prices), Decimal("0"))

print(money_sum(["0.10", "0.20", "0.30"]))

0.60


### 3. `days_between(d1, d2)`

Число дней между двумя датами. *Подсказка:* `datetime.date` и вычитание – результат
`timedelta`, у него есть `.days`.

In [69]:
from datetime import date


def days_between(d1, d2):
    return abs((d2 - d1).days)      # abs - чтобы порядок аргументов не имел значения


print(days_between(date(2026, 1, 1), date(2026, 3, 1)))
print(days_between(date(2026, 3, 1), date(2026, 1, 1)))

59
59


## Что почитать

- [Числовые типы](https://docs.python.org/3/library/stdtypes.html) – `int`, `float`,
  `complex` и операции над ними.
- [Floating Point Arithmetic](https://docs.python.org/3/tutorial/floatingpoint.html) –
  почему `0.1 + 0.2 != 0.3`; короткое и важное чтение.
- [`decimal`](https://docs.python.org/3/library/decimal.html) – точные вычисления
  там, где речь о деньгах.
